### ISSUE TITLE
StandardFirmata not working with nRF8001

### ISSUE THREAD

**Issue by eyalfoni** [adafruit/Adafruit_BLE_PinIO#8] opened 2016-01-10 20:14 UTC
Trying to run StandardFirmata (following https://learn.adafruit.com/getting-started-with-the-nrf8001-bluefruit-le-breakout/software-bluefruit-firmata) results in a lot of errors where variables are "not declared in this scope". Is there an import statement missing? Or is it something else?

**Comment by ladyada** [comment] 2016-01-10 20:54
nrf8001 isnt working quite yet, we ended up kinda breakint i. please hold, we'll close this issue once we get it working again!

**Comment by eyalfoni** [comment] 2016-01-10 21:17
thanks! is there anything specific you recommend i take a look at and see if i can get it working?

**Comment by ladyada** [comment] 2016-01-10 21:19
could go back to this commit, manually install that version :) 
https://github.com/adafruit/Adafruit_BLE_PinIO/tree/58a7b4dfbd5224d05192bd827200fcdcc597f1d8

**Comment by eyalfoni** [comment] 2016-01-10 21:53
thanks that worked great!

**Comment by resolutedreamer** [comment] 2016-07-24 05:56
Hi, I'm experiencing the same issue. I manually installed that version and it seems to work, however when I try to use my Nexus 5 and the current version of the Adafruit App the functionality is not complete. When I choose to connect in Pin I/O mode, it tries to query pin capabilities, then it says "No response to capability query, Assuming default pin format (Arduino Uno)". This is fine, except the PWM pins do not show up as PWM.

**Comment by ladyada** [comment] 2016-07-25 01:35
we recently updated this version (the current repo) with nrf8001 support - check the examples!

**Closed by ladyada** 2016-07-25 01:35 UTC

**Comment by resolutedreamer** [comment] 2016-07-25 02:54
I went to this ticket because the current version of the repo won't even compile, so I wanted to find what version would compile. Using Arduino IDE v1.6.9 and an Uno I get the error message:

Arduino: 1.6.9 (Windows 10), Board: "Arduino/Genuino Uno"

WARNING: Spurious .github folder in 'Adafruit BLEFirmata' library
StandardFirmata:63: error: 'TOTAL_PORTS' was not declared in this scope

 byte reportPINs[TOTAL_PORTS];       // 1 = report this port, 0 = silence

                 ^

StandardFirmata:64: error: 'TOTAL_PORTS' was not declared in this scope

 byte previousPINs[TOTAL_PORTS];     // previous 8 bits sent

                   ^

StandardFirmata:67: error: 'TOTAL_PINS' was not declared in this scope

 byte pinConfig[TOTAL_PINS];         // configuration of every pin

                ^

StandardFirmata:68: error: 'TOTAL_PORTS' was not declared in this scope

 byte portConfigInputs[TOTAL_PORTS]; // each bit: 1 = pin in INPUT, 0 = anything else

                       ^

StandardFirmata:69: error: 'TOTAL_PINS' was not declared in this scope

 int pinState[TOTAL_PINS];           // any value that has been written

              ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void outputPort(byte, byte, byte)':

StandardFirmata:145: error: 'portConfigInputs' was not declared in this scope

   portValue = portValue & portConfigInputs[portNumber];

                           ^

StandardFirmata:147: error: 'previousPINs' was not declared in this scope

   if(forceSend || previousPINs[portNumber] != portValue) {

                   ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void checkDigitalInputs(boolean)':

StandardFirmata:162: error: 'TOTAL_PORTS' was not declared in this scope

   for (uint8_t i=0; i<TOTAL_PORTS; i++) {

                       ^

StandardFirmata:163: error: 'reportPINs' was not declared in this scope

     if (reportPINs[i]) {

         ^

StandardFirmata:165: error: 'portConfigInputs' was not declared in this scope

       uint8_t x = readPort(i, portConfigInputs[i]);

                               ^

StandardFirmata:165: error: 'readPort' was not declared in this scope

       uint8_t x = readPort(i, portConfigInputs[i]);

                                                  ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void setPinModeCallback(byte, int)':

StandardFirmata:178: error: 'pinConfig' was not declared in this scope

   if ((pinConfig[pin] == I2C) && (isI2CEnabled) && (mode != I2C)) {

        ^

StandardFirmata:183: error: 'IS_PIN_SERVO' was not declared in this scope

   if (IS_PIN_SERVO(pin) && mode != SERVO && servos[PIN_TO_SERVO(pin)].attached()) {

                       ^

StandardFirmata:183: error: 'PIN_TO_SERVO' was not declared in this scope

   if (IS_PIN_SERVO(pin) && mode != SERVO && servos[PIN_TO_SERVO(pin)].attached()) {

                                                                    ^

StandardFirmata:186: error: 'IS_PIN_ANALOG' was not declared in this scope

   if (IS_PIN_ANALOG(pin)) {

                        ^

StandardFirmata:187: error: 'PIN_TO_ANALOG' was not declared in this scope

     reportAnalogCallback(PIN_TO_ANALOG(pin), mode == ANALOG ? 1 : 0); // turn on/off reporting

                                           ^

StandardFirmata:189: error: 'IS_PIN_DIGITAL' was not declared in this scope

   if (IS_PIN_DIGITAL(pin)) {

                         ^

StandardFirmata:191: error: 'portConfigInputs' was not declared in this scope

       portConfigInputs[pin/8] |= (1 << (pin & 7));

       ^

StandardFirmata:193: error: 'portConfigInputs' was not declared in this scope

       portConfigInputs[pin/8] &= ~(1 << (pin & 7));

       ^

StandardFirmata:198: error: 'pinState' was not declared in this scope

   pinState[pin] = 0;

   ^

StandardFirmata:201: error: 'IS_PIN_ANALOG' was not declared in this scope

     if (IS_PIN_ANALOG(pin)) {

                          ^

StandardFirmata:203: error: 'IS_PIN_DIGITAL' was not declared in this scope

       if (IS_PIN_DIGITAL(pin)) {

                             ^

StandardFirmata:204: error: 'PIN_TO_DIGITAL' was not declared in this scope

         pinMode(PIN_TO_DIGITAL(pin), INPUT); // disable output driver

                                   ^

StandardFirmata:207: error: 'pinConfig' was not declared in this scope

       pinConfig[pin] = ANALOG;

       ^

StandardFirmata:208: error: 'PIN_TO_ANALOG' was not declared in this scope

       lastAnalogReads[PIN_TO_ANALOG(pin)] = -1;

                                        ^

StandardFirmata:212: error: 'IS_PIN_DIGITAL' was not declared in this scope

     if (IS_PIN_DIGITAL(pin)) {

                           ^

StandardFirmata:214: error: 'PIN_TO_DIGITAL' was not declared in this scope

       pinMode(PIN_TO_DIGITAL(pin), INPUT); // disable output driver

                                 ^

StandardFirmata:220: error: 'pinConfig' was not declared in this scope

       pinConfig[pin] = INPUT;

       ^

StandardFirmata:228: error: 'IS_PIN_DIGITAL' was not declared in this scope

     if (IS_PIN_DIGITAL(pin)) {

                           ^

StandardFirmata:230: error: 'PIN_TO_DIGITAL' was not declared in this scope

       digitalWrite(PIN_TO_DIGITAL(pin), LOW); // disable PWM

                                      ^

StandardFirmata:232: error: 'pinConfig' was not declared in this scope

       pinConfig[pin] = OUTPUT;

       ^

StandardFirmata:236: error: 'IS_PIN_PWM' was not declared in this scope

     if (IS_PIN_PWM(pin)) {

                       ^

StandardFirmata:237: error: 'PIN_TO_PWM' was not declared in this scope

       pinMode(PIN_TO_PWM(pin), OUTPUT);

                             ^

StandardFirmata:239: error: 'pinConfig' was not declared in this scope

       pinConfig[pin] = PWM;

       ^

StandardFirmata:243: error: 'IS_PIN_SERVO' was not declared in this scope

     if (IS_PIN_SERVO(pin)) {

                         ^

StandardFirmata:244: error: 'pinConfig' was not declared in this scope

       pinConfig[pin] = SERVO;

       ^

StandardFirmata:245: error: 'PIN_TO_SERVO' was not declared in this scope

       if (!servos[PIN_TO_SERVO(pin)].attached()) {

                                   ^

StandardFirmata:246: error: 'PIN_TO_DIGITAL' was not declared in this scope

           servos[PIN_TO_SERVO(pin)].attach(PIN_TO_DIGITAL(pin));

                                                              ^

StandardFirmata:251: error: 'IS_PIN_I2C' was not declared in this scope

     if (IS_PIN_I2C(pin)) {

                       ^

StandardFirmata:254: error: 'pinConfig' was not declared in this scope

       pinConfig[pin] = I2C;

       ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void analogWriteCallback(byte, int)':

StandardFirmata:265: error: 'TOTAL_PINS' was not declared in this scope

   if (pin < TOTAL_PINS) {

             ^

StandardFirmata:266: error: 'pinConfig' was not declared in this scope

     switch(pinConfig[pin]) {

            ^

StandardFirmata:268: error: 'IS_PIN_SERVO' was not declared in this scope

       if (IS_PIN_SERVO(pin))

                           ^

StandardFirmata:269: error: 'PIN_TO_SERVO' was not declared in this scope

         servos[PIN_TO_SERVO(pin)].write(value);

                                ^

StandardFirmata:270: error: 'pinState' was not declared in this scope

         pinState[pin] = value;

         ^

StandardFirmata:273: error: 'IS_PIN_PWM' was not declared in this scope

       if (IS_PIN_PWM(pin))

                         ^

StandardFirmata:274: error: 'PIN_TO_PWM' was not declared in this scope

         analogWrite(PIN_TO_PWM(pin), value);

                                   ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void digitalWriteCallback(byte, int)':

StandardFirmata:285: error: 'TOTAL_PORTS' was not declared in this scope

   if (port < TOTAL_PORTS) {

              ^

StandardFirmata:288: error: 'TOTAL_PINS' was not declared in this scope

     if (lastPin > TOTAL_PINS) lastPin = TOTAL_PINS;

                   ^

StandardFirmata:291: error: 'IS_PIN_DIGITAL' was not declared in this scope

       if (IS_PIN_DIGITAL(pin)) {

                             ^

StandardFirmata:294: error: 'pinConfig' was not declared in this scope

         if (pinConfig[pin] == OUTPUT || pinConfig[pin] == INPUT) {

             ^

StandardFirmata:296: error: 'pinState' was not declared in this scope

           pinState[pin] = ((byte)value & mask) ? 1 : 0;

           ^

StandardFirmata:308: error: 'writePort' was not declared in this scope

     writePort(port, (byte)value, pinWriteMask);

                                              ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void reportAnalogCallback(byte, int)':

StandardFirmata:320: error: 'TOTAL_ANALOG_PINS' was not declared in this scope

   if (analogPin < TOTAL_ANALOG_PINS) {

                   ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void reportDigitalCallback(byte, int)':

StandardFirmata:334: error: 'TOTAL_PORTS' was not declared in this scope

   if (port < TOTAL_PORTS) {

              ^

StandardFirmata:336: error: 'reportPINs' was not declared in this scope

     reportPINs[port] = (byte)value;

     ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void sysexCallback(byte, byte, byte*)':

StandardFirmata:458: error: 'IS_PIN_SERVO' was not declared in this scope

       if (IS_PIN_SERVO(pin)) {

                           ^

StandardFirmata:459: error: 'PIN_TO_SERVO' was not declared in this scope

         if (servos[PIN_TO_SERVO(pin)].attached())

                                    ^

StandardFirmata:461: error: 'PIN_TO_SERVO' was not declared in this scope

         servos[PIN_TO_SERVO(pin)].attach(PIN_TO_DIGITAL(pin), minPulse, maxPulse);

                                ^

StandardFirmata:461: error: 'PIN_TO_DIGITAL' was not declared in this scope

         servos[PIN_TO_SERVO(pin)].attach(PIN_TO_DIGITAL(pin), minPulse, maxPulse);

                                                            ^

StandardFirmata:487: error: 'TOTAL_PINS' was not declared in this scope

     for (byte pin=0; pin < TOTAL_PINS; pin++) {

                            ^

StandardFirmata:488: error: 'IS_PIN_DIGITAL' was not declared in this scope

       if (IS_PIN_DIGITAL(pin)) {

                             ^

StandardFirmata:494: error: 'IS_PIN_ANALOG' was not declared in this scope

       if (IS_PIN_ANALOG(pin)) {

                            ^

StandardFirmata:498: error: 'IS_PIN_PWM' was not declared in this scope

       if (IS_PIN_PWM(pin)) {

                         ^

StandardFirmata:502: error: 'IS_PIN_SERVO' was not declared in this scope

       if (IS_PIN_SERVO(pin)) {

                           ^

StandardFirmata:506: error: 'IS_PIN_I2C' was not declared in this scope

       if (IS_PIN_I2C(pin)) {

                         ^

StandardFirmata:520: error: 'TOTAL_PINS' was not declared in this scope

       if (pin < TOTAL_PINS) {

                 ^

StandardFirmata:521: error: 'pinConfig' was not declared in this scope

         Serial.write((byte)pinConfig[pin]);

                            ^

StandardFirmata:522: error: 'pinState' was not declared in this scope

  Serial.write((byte)pinState[pin] & 0x7F);

                     ^

StandardFirmata:532: error: 'TOTAL_PINS' was not declared in this scope

     for (byte pin=0; pin < TOTAL_PINS; pin++) {

                            ^

StandardFirmata:533: error: 'IS_PIN_ANALOG' was not declared in this scope

       Serial.write(IS_PIN_ANALOG(pin) ? PIN_TO_ANALOG(pin) : 127);

                                     ^

StandardFirmata:533: error: 'PIN_TO_ANALOG' was not declared in this scope

       Serial.write(IS_PIN_ANALOG(pin) ? PIN_TO_ANALOG(pin) : 127);

                                                          ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void enableI2CPins()':

StandardFirmata:545: error: 'TOTAL_PINS' was not declared in this scope

   for (i=0; i < TOTAL_PINS; i++) {

                 ^

StandardFirmata:546: error: 'IS_PIN_I2C' was not declared in this scope

     if(IS_PIN_I2C(i)) {

                    ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void systemResetCallback()':

StandardFirmata:579: error: 'TOTAL_PORTS' was not declared in this scope

   for (byte i=0; i < TOTAL_PORTS; i++) {

                      ^

StandardFirmata:580: error: 'reportPINs' was not declared in this scope

     reportPINs[i] = false;      // by default, reporting off

     ^

StandardFirmata:581: error: 'portConfigInputs' was not declared in this scope

     portConfigInputs[i] = 0; // until activated

     ^

StandardFirmata:582: error: 'previousPINs' was not declared in this scope

     previousPINs[i] = 0;

     ^

StandardFirmata:586: error: 'TOTAL_PINS' was not declared in this scope

   for (byte i=0; i < TOTAL_PINS; i++) {

                      ^

StandardFirmata:587: error: 'IS_PIN_ANALOG' was not declared in this scope

     if (IS_PIN_ANALOG(i)) {

                        ^

C:\Users\Resol\Documents\Arduino\libraries\Adafruit_BLE_PinIO\examples\StandardFirmata\StandardFirmata.ino: In function 'void loop()':

StandardFirmata:716: error: 'TOTAL_PINS' was not declared in this scope

     for(pin=0; pin<TOTAL_PINS; pin++) {

                    ^

StandardFirmata:717: error: 'IS_PIN_ANALOG' was not declared in this scope

       if (IS_PIN_ANALOG(pin) && (pinConfig[pin] == ANALOG)) {

                            ^

StandardFirmata:717: error: 'pinConfig' was not declared in this scope

       if (IS_PIN_ANALOG(pin) && (pinConfig[pin] == ANALOG)) {

                                  ^

StandardFirmata:718: error: 'PIN_TO_ANALOG' was not declared in this scope

         analogPin = PIN_TO_ANALOG(pin);

                                      ^

exit status 1
'TOTAL_PORTS' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ladyada** [comment] 2016-07-25 02:58
can't reproduce. with the latest version of this libary, compiling Firmata_nrf8001 works just fine with UNO selected. using 1.6.9

you are compiling the nrf8001 example right?

**Comment by resolutedreamer** [comment] 2016-07-25 02:59
No, I'm compiling the example called StandardFirmata, which is the example mentioned in the title of this ticket. Let me try the other example.

**Comment by resolutedreamer** [comment] 2016-07-25 03:06
Firmata_nrf8001 uploads to Uno succesfully. However, the app still gives the same issue. Let me prepare screenshots.

**Comment by ladyada** [comment] 2016-07-25 03:07
open a new issue - but no ETA on a fix

**Comment by resolutedreamer** [comment] 2016-07-25 03:15
Okay, I understand. Can you please let me know if you are also able to reproduce the issue?
